### ISSUE TITLE
Module not found: Error: Can't resolve 'css-animation'

### ISSUE THREAD

**Issue by VinayakRugvedi** [react-component/collapse#126]
Looks like a new version of "css-animation" is out which is breaking!

**Comment by meodemsao** [comment]
@VinayakRugvedi i have same issues, when deploy project using antd-mobile

**Comment by VinayakRugvedi** [comment]
@meodemsao I guess the issue is resolved as we have an updated version of 'css-animation'
Its current version is 2.0.1 as its working fine in my case!
Is the issue still persisting in your case..?

**Comment by meodemsao** [comment]
@meodemsao because i used ant-design component that lib depend on rc-collapse

**Comment by VinayakRugvedi** [comment]
I was in a similar state wherein my project was using rc-collapse which was in turn using css-animation and the issue is resolved now!
