### ISSUE TITLE
The lib folder is missing in the  v2.1.0  package

### ISSUE THREAD

**Issue by zhangtengjin** [react-component/collapse#171]
hello ~

![image](https://user-images.githubusercontent.com/33016610/98331739-2b33bb00-2038-11eb-8356-5a7fd28fc8b2.png)
![image](https://user-images.githubusercontent.com/33016610/98331762-3686e680-2038-11eb-8737-0846e7a91d61.png)

I want to know this is a bug or there are other reasons～

**Comment by yoyo837** [comment]
你这个是源码包

下面这个才是运行包
![image](https://user-images.githubusercontent.com/6134547/98332067-ebb99e80-2038-11eb-861c-491a98628da0.png)
