### ISSUE TITLE
Dynamically show and hide panels

### ISSUE THREAD

**Issue by molson504x** [react-component/collapse#19]
I've got a scenario where I need to be able to hide and show panels dynamically.  It looks like the way your code works, even if I pass a "null" component into the collapse component as a child, it will still attempt to render a panel from that.  Is there a way where I can pass all child vars into the Collapse component, but have it not render null components?  Or is there a way on the panels where I can tell a panel not to render?

Thanks!

**Comment by shepherdwind** [comment]
I don't think pass all child vars to the Collapse is a good idea.

In React, every thing is javascript. You should handle the origin data to fit what you want. For example, If you hava an array var, which need be Collaspse.Panel elements. You should write like this:

```js
let children = [ 1, 2, 3, null]; 

<Collaspse>
{children.filter(item => item).map(item =>  <Panel>{item}</Panel>)}
</Collaspse>
```

**Comment by yiminghe** [comment]
:+1:

**Comment by molson504x** [comment]
So what you're saying here is to push my child panel items to an array, and then pass the array into the collapse?  Makes sense...  So then my code would look something like:

````javascript
render: function() {
    var collapsePanels = [];
    if (panel1)
        collapsePanels.push(<Panel>panel1</Panel>);

    if (panel2)
        collapsePanels.push(<Panel>panel2</Panel>);

    return (
        <Collapse>
            {collapsePanels}
        </Collapse>
    );
}
````

**Comment by shepherdwind** [comment]
Yes,  you can pass an array to Collapse. But, If you want handle data in Collapse, so we can skip empty panel element, pr is well come.
