### ISSUE TITLE
React 0.14 Compatibility

### ISSUE THREAD

**Issue by natorojr** [react-component/collapse#20]
This project is not technically React 0.14 compatible since one of its dependencies is not: rc-animate.

When using rc-collapse w/ React 0.14, you'll get the following warning/error in the console:

> Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

I have create this PR to update the dependencies:

rc-animate: https://github.com/react-component/animate/pull/4

**Comment by yiminghe** [comment]
1.4.0

**Comment by shepherdwind** [comment]
+1
