### ISSUE TITLE
github url on npm incorrect

### ISSUE THREAD

**Issue by karenpeng** [react-component/collapse#26]
[Package page](https://www.npmjs.com/package/rc-collapse) on npm shows incorrect github url
 > github.com/react-component/rc-collapse

**Comment by benjycui** [comment]
Fixed in https://github.com/react-component/collapse/commit/539b34450688ca66f5f860e3298dbfa916b3a9f3

**Comment by benjycui** [comment]
@yiminghe 可能要先发个 patch?

**Comment by karenpeng** [comment]
oh sorry didn't see that.

**Comment by yiminghe** [comment]
1.4.5
