### ISSUE TITLE
collpase 如何手动通过js设置activeKey？

### ISSUE THREAD

**Issue by freestyle21** [react-component/collapse#29]
在props里面设置activeKey可以实现多个collapse-item的切换：
 
    <Collapse accordion activeKey="1">
       ...
    </Collapse>

但是如何通过js手动设置activeKey，比如

     this.refs.collapse.setState({
        activeKey: 4
     })

类似的？

**Comment by shepherdwind** [comment]
都是通过 prop 控制的，没有这种直接 set 值的，不需要直接 set 的。

**Comment by freestyle21** [comment]
当需要手动设置 activeKey 的场景呢？有没有一些方法?

**Comment by shepherdwind** [comment]
设置 prop 一个方式就够了，以前 dialog 组件还有 hide 方法的，新版的都没有了。https://github.com/react-component/dialog 如果想关闭弹窗，只能设置  visible 属性了。方法调用的方式不好，得 state 和 prop 混用，统一一种方式比较好理解。

**Comment by jorisw** [comment]
If I may continue this discussion in English, I'm having trouble setting the `activeKey` through a user action that results in a setState(). My code:

```
<Collapse
     activeKey={this.state.activePanel?this.state.activePanel:'fullDetails'}
     defaultActiveKey="fullDetails"
     accordion={true} >
        <Panel header="Full Details" key="fullDetails">
...
        </Panel>
        <Panel header="Speakers" key="speakers">
...
        </Panel>
...
```


```
openPanel(key){
      this.setState({activePanel:key});
}
```

Now, when I call `openPanel('speakers')`, all the panels close, and the one with key `speakers` doesn't open.

What is the right way to open a panel from the parent component?

**Comment by shepherdwind** [comment]
@jorisw there is  an example http://react-component.github.io/collapse/examples/simple.html , and you can actvie panel this way

```
  setActivityKey() {
    this.setState({
      activeKey: ['2'],
    });
  },
```

And triggered by button

```
      <button onClick={this.setActivityKey}>active header 2</button>
```

I try to change `['2']` to `'2'` the code just run ok, so I think you code should work fine two.

Maybe you should fork my sample repo https://github.com/shepherdwind/sample-collapse(flow the readme.md step) , and write you code , so I can reproduce you problem.

**Comment by jorisw** [comment]
You're right it works. Apologies. The problem was in my code.
