### ISSUE TITLE
import Accordion from 'rc-accordion' 时报错

### ISSUE THREAD

**Issue by ggchxx** [react-component/collapse#3]
./~/rc-accordion/src/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Accordion in /Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src
resolve file
  /Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src/Accordion doesn't exist
  /Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src/Accordion.js doesn't exist
resolve directory
  /Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src/Accordion/package.json doesn't exist (directory description file)
  /Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src/Accordion doesn't exist (directory default file)
[/Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src/Accordion]
[/Volumes/ZBMOBI/React/ReactWebPackDemo/node_modules/rc-accordion/src/Accordion.js]
 @ ./~/rc-accordion/src/index.js 2:17-39

**Comment by shepherdwind** [comment]
我试下看看

**Comment by shepherdwind** [comment]
发现问题了，原来没有.npmignore，npm上是src的内容

**Comment by shepherdwind** [comment]
```
$ npm install rc-collapse
```

试试，API有所调整，默认是折叠面板，如果需要手风琴，请配置属性`accordion={true}`.

**Comment by ggchxx** [comment]
好的 我用一下
