### ISSUE TITLE
license in package.json 

### ISSUE THREAD

**Issue by ZeerDonker** [react-component/collapse#30]
Hello,

Think you may have a typo in your package file. 

``` "license": "MIT", ```
https://github.com/nkbt/react-collapse/blob/master/package.json 

 ```  "licenses": "MIT",  ```
https://github.com/react-component/collapse/blob/master/package.json

Tried to add your npm package as a webjar on http://www.webjars.org/npm.
(Add a new npm webjar button)

And got the following error. 
 ```
Failed! All attempts to determine a license have been exhausted. 
The bower.json did not contain a spec-compliant license definition 
and the license could not be determined by trolling through the GitHub repo. 
This problem will likely need to be resolved by working with the library maintainers directly. 
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Determined Artifact Name: rc-collapse Starting Deploy
 ```

**Comment by shepherdwind** [comment]
Thanks for you advice . licenses key is valid now. Merge request is welcome too .

**Comment by afc163** [comment]
https://github.com/react-component/tree-select/blob/master/package.json#L24

All components in https://github.com/react-component/ have same issue.
