### ISSUE TITLE
Animation lagging

### ISSUE THREAD

**Issue by jasonblanchard** [react-component/collapse#31]
After the 1.5.0 upgrade that includes the switch to using CSS animations, the open/close animation is very slow and lags in all browsers.

**Comment by shepherdwind** [comment]
@yiminghe May be you should see this.

**Comment by yiminghe** [comment]
try to upgrade and override https://github.com/react-component/collapse/blob/master/assets/index.less#L30

**Comment by jorisw** [comment]
I have the same problem with version 1.6.3 that is currently in npm.
