### ISSUE TITLE
Server-side rendering issues

### ISSUE THREAD

**Issue by dimaip** [react-component/collapse#32]
Hey, rc-collapse seems to have issues with server side rendering, because of rc-animate:

```
client.js:4 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) .$rc_animate_1460040782855"><div class="
 (server) .$rc_animate_1460040116046"><div class="
```

Any way to fix it?

**Comment by shepherdwind** [comment]
I try rc-collapse on server side render. But, there no any problem. May be you can try upgrade all package to the latest version.

**Comment by shepherdwind** [comment]
Or you can give a example to repeat this problem.

**Comment by dimaip** [comment]
@shepherdwind really really weird. I tried to reproduce it now, but couldn't anymore. When I recompiled the project, the problem was gone. If it ever happens again and I can reliably reproduce it, I'll get back in touch.
Thanks for the great package!
