### ISSUE TITLE
Documentation of 'activekey' prop inconsistent

### ISSUE THREAD

**Issue by jorisw** [react-component/collapse#34]
The documentation for this project says the component accepts prop `activeKey` here and `activekey` in the example. Should be `activekey`, according to the code in the component.

**Comment by shepherdwind** [comment]
> Should be activekey, according to the code in the component.

But I can't find any code like `activekey`.  Such as https://github.com/react-component/collapse/blob/master/src/Collapse.jsx#L17 .

**Comment by jorisw** [comment]
The docs however mention `activekey` instead of `activeKey`.
