### ISSUE TITLE
prefixCls undocumented?

### ISSUE THREAD

**Issue by danpantry** [react-component/collapse#40]
There's an immensely useful prop on `Container` called `prefixCls`. It's not in any documentation. Is it safe to use this?

**Comment by shepherdwind** [comment]
`prefixCls` is safe to use, but you need change the `@prefixCls` in less file https://github.com/react-component/collapse/blob/master/assets/index.less. So you need write style your self.

**Comment by danpantry** [comment]
That's completely fine, that's what I actually want.
