### ISSUE TITLE
Use Panel Component inside another component instead direct child

### ISSUE THREAD

**Issue by jmgarciamari** [react-component/collapse#46]
Hi! I'm trying to build a collapsable menu but I need "Panel" component inside another component and it don't works... 
Is it necessary for Panel to be the direct child of Collapse?

Thanks

**Comment by shepherdwind** [comment]
If you want menu, you should try this https://ant.design/components/menu/?locale=en-US .

Or this menu component https://github.com/react-component/menu

**Comment by jmgarciamari** [comment]
Thanks!
