### ISSUE TITLE
Question: Is it possible to change the direction of the expand?

### ISSUE THREAD

**Issue by WilliamHolmes** [react-component/collapse#51]
By default the accordion expand direction is top-down.

Is it currently possible to change the expand direction from top-down to bottom-up?

**Comment by benjycui** [comment]
It is a weirdo UX, could you post some sample that other components had support this UX?

**Comment by lauterry** [comment]
Hi

I also have this use case.

It would be great to be able to expand bottom-up

Best regards

**Comment by benjycui** [comment]
rc-collapse is jsut a simple component, and we are not going to support complex behavior.

So, just implement your own, thanks.
