### ISSUE TITLE
 Unexpected token: name (Collapse) [../~/rc-collapse/src/index.js:1,0]

### ISSUE THREAD

**Issue by rabishah** [react-component/collapse#53]
I had forked this repository to [27AE60/collapse](https://github.com/27AE60/collapse).
Then I ran, `npm install --save 27ae60/collapse` 

But, when I build my project `npm run install` it says `Unexpected token: name (Collapse)...`
Am I missing some steps here in order to use the forked repository?

**Comment by benjycui** [comment]
Try to upgrade you Node.js to the latest version.

**Comment by benjycui** [comment]
And you need to run `npm run pub` instead of `npm publish` if you are publishing your own npm package, see: https://github.com/react-component/collapse/blob/master/package.json#L35

**Comment by rabishah** [comment]
Thanks @benjycui
