### ISSUE TITLE
Question: Why not have className as props for Collapse component?

### ISSUE THREAD

**Issue by ivolivares** [react-component/collapse#54]
Hi!

I use `rc-collapse` in my project but I prefer define my own `className` for my components.
Any reason to not have yet this prop?

Thanks!

**Comment by shepherdwind** [comment]
You can overwrite prop `prefixCls` .  Code at https://github.com/react-component/collapse/blob/master/src/Collapse.jsx#L133

**Comment by ivolivares** [comment]
what's the problem to make available `className` prop? I think things like that it's responsibility of app and not the libraries like "rc-collapse".

Why yes in `Collapse.Panel` and not in `Collapse` container?

**Comment by shepherdwind** [comment]
Do you really try to use the `className` prop? 

![image](https://cloud.githubusercontent.com/assets/452899/24103235/9d740cd2-0db9-11e7-8a87-c278cd9114c6.png)

The `className` prop is work fine, see code at https://github.com/react-component/collapse/blob/master/src/Collapse.jsx#L135

**Comment by benjycui** [comment]
@shepherdwind maybe we can add this API in README.md...

**Comment by GeoMarkou** [comment]
I can't seem to use `className` / `prefix` / `id` properties on the <Collapse> element in version `5.1.1`. Makes it difficult to style using CSS.
