### ISSUE TITLE
I get a React Warning when rendering divs as children in Collapse component

### ISSUE THREAD

**Issue by BrockBeldham** [react-component/collapse#56]
My looks like this:
```
<Collapse
  accordion
  activeKey={this.state.activeKey}
  onChange={(activeKey) => this.setState({ activeKey })}>
  <Panel header='test'>
    ...
  </Panel>
  <div>
    Content that I don't want to be included in the accordion
  </div>
  <Panel header='also a test'>
    ...
  </Panel>
</Collapse>
```
It renders and operates as expected, but I get a React warning:

Warning: Unknown props 'header', 'isActive', 'prefixCls', 'openAnimation', 'onItemClick' on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

The error goes away when I only use Panels as children in the Collapse component. But my project design requires that the accordion operate as one accordion even though there are some elements that are in between the accordion panels. Not a high priority as it renders and operates as expected, just thought the warning message should be reported.

**Comment by benjycui** [comment]
Only `Collapse.Panel` can be direct children of `Collapse`, @shepherdwind we should add a warning for this.

**Comment by BrockBeldham** [comment]
Personally, I think there is a use case for non-Panel elements as children of Collapse. Or maybe you can add an 'alwaysOpen' prop to the Panel component, so that it could be combined with a css class to make it look like that Panel element isn't a Panel component.

**Comment by shepherdwind** [comment]
You can control the prop `activeKey`, which can be an array. Just set the key of Panel which you want alwaysOpen to be one of activeKey element.

For example, you code can be like this

```js
  onChange(activeKey) {
    activeKey.push(theKeyShouldAlwaysOpen);
    this.setState({ activeKey });
  },
```

**Comment by BrockBeldham** [comment]
right, but in order to use the array for an active key, I need to set accordion to false. I want to use the accordion functionality, while either leaving some Panels open (which functionally doesn't make sense) or have non-Panel elements as children to Collapse.

**Comment by benjycui** [comment]
> right, but in order to use the array for an active key, I need to set accordion to false. I want to use the accordion functionality, while either leaving some Panels open (which functionally doesn't make sense) or have non-Panel elements as children to Collapse.

Nope, actually, your expected behavior is conflict with `accordion`, just follow @shepherdwind 's suggestion.
