### ISSUE TITLE
Programmatically setting the expand/collapse state

### ISSUE THREAD

**Issue by rakeshpai** [react-component/collapse#60]
I am not able to programatically set the state of the Panel. I've tried setting `<Panel isActive={true} />` but it doesn't seem to work. I've tried setting `<Collapse activeKey='0'>...`. and while this works, it only lets me specify one panel to be opened. The docs mention passing an array to activeKey, but I couldn't get it to work, and couldn't find any examples of it.

In my case, I need all the panels to be expanded at startup by default. Any idea how I can do this?

**Comment by shepherdwind** [comment]
You change set the activeKey value. For example

```jsx
      const activeKey = ['1', '2', '3'];
      <Collapse
        accordion={accordion}
        onChange={this.onChange}
        activeKey={activeKey}
      >
        {this.getItems()}
      </Collapse>

```

**Comment by rakeshpai** [comment]
Ah, it needs an array of strings! That fixed my issue. Thanks.

**Comment by Mohamed-Ghanem** [comment]
@shepherdwind isn't this make the Collapse controlled?
What if I just want to set all of panels to active and I don't have the keys as they are unique strings based on the object being rendered, not indices.
