### ISSUE TITLE
accordion={true} not working

### ISSUE THREAD

**Issue by yuripramos** [react-component/collapse#63]
> If accordion is true, only one panel can be open. Opening another panel will cause the previously opened panel to close. activeKey should be an string, if passing an array (the first item in the array will be used).
> 

Here's my snippet: 
```

  render(){
    const stateStyle = this.state.active ? styles.active : styles.inactive;

    const Materias = this.props.items.map((item, key)=>(
        <Panel header={item.title} key={key}>
          <HeaderComponent title={item.title} id={item.id} subtitle={item.subtitle} category={item.categoria}/>
          <Content content={item.content[0]}/>
          <Footer />
        </Panel>
    )); 
    return (
      <div className={style.container}>
        <Collapse accordion={true}>
          {Materias}
        </Collapse>
      </div>
    );
  }
```

Actually im rendering 3 panels, and even with the accordion prop = true_ I can open the 3 at the same time.

**Comment by shepherdwind** [comment]
Can you provide a complete example?

For example, fork this repo, and run `npm i && npm start`,Then modify the demo file https://github.com/react-component/collapse/blob/master/examples/simple.js . And push you demo code to github, So I can repeat the problem you meeting.

**Comment by yuripramos** [comment]
After adapting your demo to my project I realized that the problem is inside my project. Still don't know what to do to solve this, but the accordion and the hide panel don't work.

**Comment by danawhite** [comment]
@yuripramos I just installed the library and am experiencing the same issue. have you resolved this issue by any chance?

**Comment by yuripramos** [comment]
@danawhite  Not yet, I'm using another repo. Look for react-sanfona. Good Luck!
