### ISSUE TITLE
Not showing arrow

### ISSUE THREAD

**Issue by jstray** [react-component/collapse#64]
In the default configuration, or with showArrow=true, I'm not seeing an arrow. 

```
        <Collapse>
          <Panel header='Output'>
            <DataGrid idProperty="index" dataSource={tableData} columns={columns} />
          </Panel>
        </Collapse>

```

This is using Bootstrap 4, if that makes a difference.

**Comment by jstray** [comment]
Ah, needed to include the CSS:
```
require('rc-collapse/assets/index.css');
```
Would have been helpful to see this in the examples.

**Comment by shepherdwind** [comment]
I add this to doc file README.md now, It is seems a lot of this kind problem.
