### ISSUE TITLE
Can only open, not close a panel

### ISSUE THREAD

**Issue by jstray** [react-component/collapse#65]
Clicking on the panel header opens it, but clicking on it again it flashes closed for a moment and then re-opens. I would expect it to toggle

```
        <Collapse>
          <Panel header='Output'>
            <DataGrid idProperty="index" dataSource={tableData} columns={columns} />
          </Panel>
        </Collapse>

```
There is only one panel in this example, but it happens even if I add another panel. This is under Bootstrap 4.

**Comment by jstray** [comment]
Solved: need to include CSS 
```
require('rc-collapse/assets/index.css');
```

**Comment by shepherdwind** [comment]
Document file updated now.
