### ISSUE TITLE
Html code inside Panel header?

### ISSUE THREAD

**Issue by BijayRai** [react-component/collapse#68]
is there any way to place Html code inside Panel header?

**Comment by benjycui** [comment]
Just use JSX:

```jsx
<Collapse>
  < Panel header={<span>aaa</span>} />
</Collapse>
```

**Comment by qborreda** [comment]
You can also use other components inside.

**Comment by tim-soft** [comment]
@benjycui @qborreda How could you incorporate a component such as a button inside the collapse panel header? Clicking the button will collapse/expand the panel.

```js
<Collapse>
  < Panel header={<Button>Click Me</Button>} />
</Collapse>
```

**Comment by BijayRai** [comment]
@tim-soft  You can use `event.preventDefault ` for that on Button click function.

**Comment by tim-soft** [comment]
The problem here is that `<Collapse >`'s `onChange` function will fire before a `<Panel />` header component could prevent the behavior

**Comment by benjycui** [comment]
stopPropagation
