### ISSUE TITLE
Allow to set 'id' attribute to the panel

### ISSUE THREAD

**Issue by mikhailChibel** [react-component/collapse#69]
Is there any way to set id attribute to the panel?

**Comment by benjycui** [comment]
Nope, just use:

```jsx
<Panel>
  <div id="..."></div>
</Panel>
```

**Comment by benjycui** [comment]
@shepherdwind I am not sure if we can pass rest props to panel? https://github.com/react-component/collapse/blob/f6ea09b747f976f92b9838d0ccb52c770df2c45b/src/Panel.jsx#L14-L22

**Comment by mikhailChibel** [comment]
@benjycui sure I can set id on the content of the panel. I would be nice to have an id of the panel itself, as can simplify for example UI tests.

**Comment by paranoidjk** [comment]
nope. There should never be a id api，but we may consider pass down rest props

**Comment by shepherdwind** [comment]
Rest props pass to panel is ok. But, I think that React will throw error when pass an unknown prop to panel.

**Comment by paranoidjk** [comment]
> Rest props pass to panel is ok. But, I think that React will throw error when pass an unknown prop to panel.

IMO, This is not our concern, we just need to make sure all api which shown in doc are handled, then rest props should be all html valiad.

**Comment by mikhailChibel** [comment]
@benjycui Any hope on resolving this issue anytime soon?

**Comment by benjycui** [comment]
ping @shepherdwind

**Comment by shepherdwind** [comment]
Pass rest props to panel div will give it too much useless prop. 

So, The only way is to add a prop id , see mr #72

**Comment by shepherdwind** [comment]
1.7.6
