### ISSUE TITLE
Suggestion:  ESLint warning at Panel className prop

### ISSUE THREAD

**Issue by qborreda** [react-component/collapse#75]
Due to recent changes to ESLint react rules, having a component with a prop named `className` results in a warning `Prop 'className' is forbidden on Components  react/forbid-component-props`. 

It's obvious that having className passed down to the actual DOM element is a valid workflow, thus it's only a warning, but results in it being confusing. 

This is the rule description: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md

**Comment by benjycui** [comment]
???

I don't understand. `className` is a useful API, we are not going to remove it. So, you had better disable the rule.

Actually, this rule is meaningless, according to me.

**Comment by benjycui** [comment]
Close for no response
