### ISSUE TITLE
Suggestion: multiline headers

### ISSUE THREAD

**Issue by jukkaturunen** [react-component/collapse#76]
In case header is wider than collapse box the rest of header will simply overflow. Perhaps an option to wrap lines or hide overflow?

**Comment by benjycui** [comment]
Just update rc-collapse's style is enough, see: https://github.com/ant-design/ant-design/commit/9d39a55604c692a2ed2abef289918d0668e56892

PR is welcomed. @jukkaturunen

**Comment by benjycui** [comment]
ping~

**Comment by bertho-zero** [comment]
Fixed in #95
