### ISSUE TITLE
Safari 下折叠动画闪动

### ISSUE THREAD

**Issue by zhujun24** [react-component/collapse#8]

**Comment by simaQ** [comment]
Safari 下使用 transition 都会有闪动的问题，可以加个 `transform: translate3d(0, 0, 0);` 试试

**Comment by afc163** [comment]
ping~

**Comment by shepherdwind** [comment]
safari都没人用吧

**Comment by shepherdwind** [comment]
似乎其他组件都没有问题啊

**Comment by afc163** [comment]
safari 挺多人用的。。。特别是 boss。

**Comment by shepherdwind** [comment]
找到原因了，动画结束后删除高度导致有问题

**Comment by shepherdwind** [comment]
动画结束后，设置面板高度为auto，这时候在Safari里面动画会重新跑一遍，去掉最后的设置高度就没问题了。

不过如果去掉height，就会有其他问题了。我再研究研究

**Comment by jljsj33** [comment]
设为0吧，再把style删掉，好像就不会有这问题，auto和number间无动画的吧。。

**Comment by afc163** [comment]
可以用 https://github.com/react-component/animate 试试？

**Comment by shepherdwind** [comment]
那个animate一样啊，动画原理是一样的，而且感觉有点复杂。

现在的问题是，在Safari中，把高度从固定的像素改为auto的时候，会重新动一遍。

bootstrap的解决方案是，动画接中，加一个collapsing的class，然后结束后把collapsing删掉，动画相关的配置在collapsing上，这样，动画结束后，设置高度为auto的时候，就不会有动画了。

**Comment by jljsj33** [comment]
看下导航的拆叠样式，承玉的animate用的是js执行动画的。。

**Comment by jljsj33** [comment]
Style.height=""试试？

**Comment by shepherdwind** [comment]
@jljsj33 都试过了

- style.hegith = ''
- el.style.cssText = ''

都一样

**Comment by shepherdwind** [comment]
我还是bootstrap的方案吧

**Comment by jljsj33** [comment]
http://react-component.github.io/menu/examples/antd.html这个有用没，，最后一个

**Comment by shepherdwind** [comment]
这个是js动画，我看下怎么写的

**Comment by shepherdwind** [comment]
js动画使用velocity实现的

**Comment by jljsj33** [comment]
Css可以试试，不要在Mout里处理height,直接用display为none，在-anim里设去掉display ，再获取a=el.offsetHeight，再设置el.style.height=0;el.ffsetHeight再设el.style.height=a,,,,我记得我那个antd里的MenuAnimation里是这样搞的。。只要再去算一次el.offsetHeight，就有transition就有效果了，dispaly设了也没关系。。

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/blob/menuAnimation/components/menu/index.jsx 跟tag的一样的，试试？

**Comment by shepherdwind** [comment]
en 我看下你在这个怎么搞的

**Comment by afc163** [comment]
现在 safari 下收回的时候没动画。
其他浏览器点快了都没动画。

**Comment by shepherdwind** [comment]
Safari那个动画是有的，就是比较快。

快速点击确实有问题，@afc163 是个好测试啊。

**Comment by yiminghe** [comment]
请用 velocity-animate ，现在的代码没法看，
