### ISSUE TITLE
Opening all Panels from the beginning

### ISSUE THREAD

**Issue by oodesign** [react-component/collapse#91]
Hi!

Is there any way to have all panels as active? 
I've seen defaultActiveKey and activeKey may be arrays, but not getting it to work...

Thanks!

**Comment by oodesign** [comment]
Found it, thanks!

**Comment by fartinmartin** [comment]
@oodesign do you remember how you got this to work? I'm not having much luck.

**Comment by oodesign** [comment]
Hi!

Sorry, I don't remember and don't have access to that project anymore, so can't check the solution.

Anyway, if that may be a number or an array, shouldn't it be something like activeKey: [ '2' , '3' , '4' ] ?

In their own examples (in simple.js), if you try the following it works fine.

`setActivityKey = () => {
    this.setState({
      activeKey: ['2','3','4'],
    });
  }`

Hope it helps!

**Comment by fartinmartin** [comment]
Hey! Thanks so much for your reply! That was definitely the problem, haha, I appreciate it!
