### ISSUE TITLE
All Panels make a new render when opening/closing a Panel.

### ISSUE THREAD

**Issue by bertho-zero** [react-component/collapse#94]
I need to do this to avoid this behavior:
```js
import _ from 'lodash';
import RCCollapse from 'rc-collapse';
import { shouldUpdate, shallowEqual } from 'recompose';

const Collapse = shouldUpdate(
  ( props, nextProps ) => (
    !shallowEqual( _.omit( props, 'children' ), _.omit( nextProps, 'children' ) )
    || !_.isEqual( props.children.map( v => v.key ), nextProps.children.map( v => v.key ) )
  )
)( RCCollapse );

const Panel = shouldUpdate(
  ( props, nextProps ) => !shallowEqual(
    _.omit( props, 'onItemClick' ),
    _.omit( nextProps, 'onItemClick' )
  )
)( RCCollapse.Panel );
```

Whether the `onItemClick` function changes or not does not affect the rendering, so you do not need to rerender when this prop changes.

**Comment by klauco** [comment]
Hello, I am also facing the same issue as @bertho-zero - for larger number of panels in one collapse this actually causes a significant performance hit.

**Comment by bertho-zero** [comment]
@klauco The problem is that Collapse creates functions inside the render:

https://github.com/react-component/collapse/blob/43c8806898aa044abaeed57457571321f14d1e36/src/Collapse.jsx#L89

https://github.com/react-component/collapse/blob/43c8806898aa044abaeed57457571321f14d1e36/src/Collapse.jsx#L67

Both of these methods must absolutely be instance methods.

**Comment by bertho-zero** [comment]
https://github.com/react-component/collapse/blob/43c8806898aa044abaeed57457571321f14d1e36/src/PanelContent.jsx#L6-L8

And this `shouldComponentUpdate` is bad.
